name: "Run tests with workflow_call"

on:
  workflow_call:
    inputs:
      ref:
        description: "git ref to checkout to"
        type: string
        default: "main"

jobs:
  tests:
    name: "build"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: fluencelabs/frpc
          ref: ${{ inputs.ref }}

      - name: Setup fcli
        uses: fluencelabs/setup-fluence@v1
        with:
          version: stage

      - name: Check if main.aqua compiles
        run: fluence aqua --dry

      - name: Check if services builds
        run: fluence build
