name: "Run tests with workflow_call"

on:
  workflow_call:
    inputs:
      ref:
        description: "git ref to checkout to"
        type: string
        default: "main"
      nox-image:
        description: "nox image tag"
        type: string
        default: "null"
      fcli-version:
        description: "fcli version to use"
        type: string
        default: "unstable"
      js-client-version:
        description: "@fluencelabs/js-client version"
        type: string
        default: "null"
      fluence-env:
        description: "env to run tests against"
        type: string
        default: "local"

jobs:
  tests:
    name: "Run tests"
    runs-on: linux-amd64-m-xlarge

    env:
      FLUENCE_USER_DIR: "${{ github.workspace }}/tmp/.fluence"
      CI: true
      # FORCE_COLOR: true

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: fluencelabs/frpc
          ref: ${{ inputs.ref }}

      - name: Import secrets
        uses: hashicorp/vault-action@v2.8.0
        with:
          url: https://vault.fluence.dev
          path: jwt/github
          role: ci
          method: jwt
          jwtGithubAudience: "https://github.com/fluencelabs"
          jwtTtl: 300
          secrets: |
            kv/hub.docker.com/fluencebot username | DOCKER_HUB_USERNAME ;
            kv/hub.docker.com/fluencebot password | DOCKER_HUB_PASSWORD ;
            kv/docker-registry/basicauth/ci username | DOCKER_USERNAME ;
            kv/docker-registry/basicauth/ci password | DOCKER_PASSWORD ;
            kv/npm-registry/basicauth/ci token | NODE_AUTH_TOKEN ;
            kv/ci/frpc chain_urls | RPC_PROVIDERS ;
            kv/ci/frpc private_key | FLUENCE_CHAIN_PRIVATE_KEY

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}

      - name: Login to private registry
        uses: docker/login-action@v3
        with:
          registry: docker.fluence.dev
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Setup Rust toolchain
        uses: dsherret/rust-toolchain-file@v1

      - name: Add wasi target
        run: rustup target add wasm32-wasi

      - name: Setup fcli
        uses: fluencelabs/setup-fluence@v1
        with:
          artifact: fcli
          version: ${{ inputs.fcli-version }}

      - name: Install aqua deps
        run: fluence dep i --no-input

      - name: Build fluence project
        run: fluence build --no-input

      - name: Init local env with fcli
        run: fluence local init --no-input

      - name: Replace nox image in docker-compose
        if: inputs.nox-image != 'null'
        working-directory: .fluence
        run: |
          sed -i'' -e '/nox-/!b;n;s|image: fluencelabs/nox:.*$|image: ${{ inputs.nox-image }}|' docker-compose.yaml

      - name: Run local env
        run: fluence local up --no-input

      - name: Setup node with self-hosted registry
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://npm.fluence.dev"
          cache: "npm"

      - name: Set js-client version
        if: inputs.js-client-version != 'null'
        uses: fluencelabs/github-actions/npm-set-dependency@main
        with:
          package: "@fluencelabs/js-client"
          version: "${{ inputs.js-client-version }}"
          working-directory: gateway

      - name: Run npm i
        run: npm i

      - name: Run npm run build
        run: npm run build

      - name: Run tests
        env:
          FLUENCE_ENV: ${{ inputs.fluence-env }}
        run: npm run test -- -t deploy

      - name: Dump container logs
        if: always()
        uses: jwalton/gh-docker-logs@v2
