name: "Run tests with workflow_call"

on:
  workflow_call:
    inputs:
      ref:
        description: "git ref to checkout to"
        type: string
        default: "main"

jobs:
  tests:
    name: "build"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: fluencelabs/frpc
          ref: ${{ inputs.ref }}

      - name: Install fluence-cli@unstable
        run: npm i -g @fluencelabs/cli@unstable

      - name: Check if main.aqua compiles
        run: fluence aqua --dry

      - name: Check if services builds
        run: fluence build
